// Generated by scripts/scaffold-video.ts on 2026-05-23.
// Re-running the scaffolder with the same id will overwrite this file.

import type { VideoModule } from "./types";

export const calmWeddingDayStructure: VideoModule = {
  "id": "CalmWeddingDayStructure",
  "title": "The Couples Who Feel Calmest: The One Thing They Do",
  "templateId": "nuptial-promo",
  "formats": [
    {
      "suffix": "Reel",
      "width": 1080,
      "height": 1920
    },
    {
      "suffix": "Square",
      "width": 1080,
      "height": 1080,
      "propOverrides": {
        "showLowerThird": false
      }
    }
  ],
  "script": {
    "metadata": {
      "videoType": "informational",
      "audience": "engaged-couples",
      "funnelStage": "interest",
      "platforms": [
        "instagram-reels",
        "tiktok",
        "facebook-reels"
      ],
      "psychologicalAngle": "loss-aversion",
      "tags": [
        "planning-mindset",
        "stress-relief",
        "structure"
      ]
    },
    "lines": [
      {
        "id": "scene-01-hook",
        "text": "The calmest couples on their wedding day all did one thing: they stopped holding it all in their heads."
      },
      {
        "id": "scene-02-sixmonths",
        "text": "Six months out, they had a vendor list. No panic. No wondering who they'd already called."
      },
      {
        "id": "scene-03-threemonths",
        "text": "Three months out, their RSVP tracker was running. They knew exactly who was coming."
      },
      {
        "id": "scene-04-onemonth",
        "text": "One month out, they weren't adding new tasks. Everything was already sequenced."
      },
      {
        "id": "scene-05-solution",
        "text": "Nuptial builds this structure for you automatically, based on your wedding date."
      },
      {
        "id": "scene-06-cta",
        "text": "Stop trying to remember everything. Start planning with peace of mind. Visit nuptial dash p h dot com."
      }
    ],
    "scenes": [
      {
        "id": "scene-01-hook",
        "headline": "Calm starts here.",
        "subhead": "They stopped holding it all in their heads.",
        "headlineVariants": {
          "curiosity": "Why some couples\nfeel zero stress.",
          "contrarian": "Wedding planning\ndoesn't have to hurt.",
          "transformation": "From chaos to\nmagic in one move."
        },
        "motionNotes": "Fade to black, then single word reveal with staggered timing: 'Calm.' 'Clarity.' 'Peace.' Each appears briefly, building rhythm."
      },
      {
        "id": "scene-02-sixmonths",
        "headline": "6 months: Vendor list.",
        "subhead": "No decisions repeated.\nNo forgotten calls.",
        "headlineVariants": {
          "value": "Everything vendors\nin one place.",
          "curiosity": "What happens when\nyou write it down?",
          "social-proof": "10,000+ couples\nplan this way."
        },
        "motionNotes": "Checklist icon slides in from left with subtle bounce. Items tick off one by one with satisfying micro-animation. Light pulse on final check."
      },
      {
        "id": "scene-03-threemonths",
        "headline": "3 months: RSVP tracker.",
        "subhead": "Know exactly who's\ncoming. Always.",
        "headlineVariants": {
          "value": "Guest count,\nat a glance.",
          "curiosity": "One number that\nchanges everything.",
          "transformation": "Certainty instead\nof guessing."
        },
        "motionNotes": "Live counter ticking upward with each guest response. Numbers animate with gentle scale-up. Color shift from grey (pending) to green (confirmed) flowing left to right."
      },
      {
        "id": "scene-04-onemonth",
        "headline": "1 month: Task sequence.",
        "subhead": "Only do what's due\nthis week.",
        "headlineVariants": {
          "value": "No overwhelm.\nNo forgotten steps.",
          "transformation": "One week, one list.",
          "curiosity": "What if you only\nworried about today?"
        },
        "motionNotes": "Timeline with 4 weeks flowing vertically. Current week highlighted and enlarged. Subtle pulse on active tasks. Previous weeks fade out, future weeks stay muted."
      },
      {
        "id": "scene-05-solution",
        "headline": "Nuptial automates it.",
        "subhead": "Structure built just for\nyour wedding date.",
        "headlineVariants": {
          "value": "Automated planning\nbased on your date.",
          "curiosity": "What does a\nplanning system know?",
          "transformation": "From spreadsheets\nto strategy."
        },
        "motionNotes": "App interface slides in. Date selector prominently displayed. Calendar morphs into task timeline. All animations fluid and calm, no jarring cuts."
      },
      {
        "id": "scene-06-cta",
        "headline": "Plan without the panic.",
        "subhead": "nuptial-ph.com",
        "headlineVariants": {
          "value": "Start your calm\nplanning now.",
          "transformation": "Stop stressing.\nStart celebrating.",
          "social-proof": "Join 10,000+ calm couples."
        },
        "motionNotes": "CTA card slides up with soft shadow. URL glows subtly. Brief pause, then gentle scale pulse on the entire card to draw final attention."
      }
    ],
    "cta": {
      "headline": "Plan without the panic.",
      "subhead": "Start free at nuptial-ph.com",
      "url": "nuptial-ph.com"
    }
  }
};
