// Generated by scripts/scaffold-video.ts on 2026-05-23.
// Re-running the scaffolder with the same id will overwrite this file.

import type { VideoModule } from "./types";

export const weddingPrepTimeBreakdown: VideoModule = {
  "id": "WeddingPrepTimeBreakdown",
  "title": "Why Wedding Prep Takes More Than 6 Hours",
  "templateId": "nuptial-promo",
  "formats": [
    {
      "suffix": "Reel",
      "width": 1080,
      "height": 1920
    },
    {
      "suffix": "Square",
      "width": 1080,
      "height": 1080,
      "propOverrides": {
        "showLowerThird": false
      }
    }
  ],
  "script": {
    "metadata": {
      "videoType": "informational",
      "audience": "engaged-couples",
      "funnelStage": "awareness",
      "platforms": [
        "instagram-reels",
        "tiktok",
        "facebook-reels"
      ],
      "psychologicalAngle": "pain-relief",
      "tags": [
        "wedding-planning",
        "education",
        "time-management"
      ]
    },
    "lines": [
      {
        "id": "scene-01-hook",
        "text": "If wedding planning feels endless, you're not imagining it."
      },
      {
        "id": "scene-02-logistics",
        "text": "First, you're managing a guest list, tracking RSVPs, and building a seating chart. That's two hours minimum."
      },
      {
        "id": "scene-03-budget",
        "text": "Then comes the budget spreadsheet. Comparing vendors, logging expenses, staying sane. Add another hour and a half."
      },
      {
        "id": "scene-04-invites",
        "text": "Digital invitations might seem simple. But designing them, personalizing messages, chasing replies? Another hour."
      },
      {
        "id": "scene-05-payoff",
        "text": "That's six hours. And that's just the basics. Nuptial brings it all together in one beautiful, simple place. Start free at nuptial dash p h dot com."
      }
    ],
    "scenes": [
      {
        "id": "scene-01-hook",
        "headline": "Six hours?\nTry twelve.",
        "subhead": "Here's where your time really goes.",
        "headlineVariants": {
          "curiosity": "Why planning takes\nso much longer than expected.",
          "value": "The real time cost\nof wedding prep.",
          "contrarian": "You're not slow.\nYour tools are."
        }
      },
      {
        "id": "scene-02-logistics",
        "headline": "Step 1: The Guest List.",
        "subhead": "Tracking names, RSVPs, plus-ones, diet restrictions, seating conflicts—scattered across emails and notes.",
        "headlineVariants": {
          "value": "One spreadsheet?\nMore like ten.",
          "curiosity": "Why your inbox is chaos.",
          "transformation": "From scattered to\norganized instantly."
        }
      },
      {
        "id": "scene-03-budget",
        "headline": "Step 2: The Budget.",
        "subhead": "Venue, catering, flowers, music, photography. Each vendor quoted differently. Each expense logged separately.",
        "headlineVariants": {
          "value": "Stop tabs switching.\nStart seeing the real number.",
          "contrarian": "One missed entry ruins\nyour whole budget.",
          "transformation": "From chaos to\ncomplete clarity."
        }
      },
      {
        "id": "scene-04-invites",
        "headline": "Step 3: The Invitations.",
        "subhead": "Designing, sending, personalizing, chasing RSVPs. Manually. One at a time.",
        "headlineVariants": {
          "value": "Beautiful invites\nthat track themselves.",
          "curiosity": "What if your invites\nalso collected RSVPs?",
          "transformation": "From manual chasing\nto automatic replies."
        }
      },
      {
        "id": "scene-05-payoff",
        "headline": "It doesn't have to\ntake this long.",
        "subhead": "One app for guests, RSVPs, seating, budget, invites.",
        "headlineVariants": {
          "value": "Cut your planning\ntime in half.",
          "transformation": "Reclaim your\nengagement time.",
          "social-proof": "Loved by couples\nwho chose calm."
        }
      }
    ],
    "cta": {
      "headline": "Start planning free.",
      "subhead": "nuptial-ph.com",
      "url": "nuptial-ph.com"
    }
  }
};
