// Take a video spec JSON (from stdin or a file path) and scaffold a new
// generated video module under src/content/videos/<id>.ts. Idempotently
// updates src/content/videos/index.ts to import and register it.
//
// Usage:
//   tsx scripts/scaffold-video.ts path/to/spec.json
//   cat spec.json | tsx scripts/scaffold-video.ts -
//
// Spec shape (minimum):
//   {
//     "id": "WhyWeddingPrep6Hours",            // PascalCase, used as module + composition prefix
//     "title": "Why wedding prep takes 6+ hours",
//     "templateId": "nuptial-promo",
//     "formats": [
//       { "suffix": "Reel", "width": 1080, "height": 1920 },
//       { "suffix": "Square", "width": 1080, "height": 1080, "propOverrides": { "showLowerThird": false } }
//     ],
//     "script": { "metadata": {...}, "lines": [...], "scenes": [...], "cta": {...} }
//   }

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const ROOT = process.cwd();
const VIDEOS_DIR = join(ROOT, "src", "content", "videos");
const INDEX_PATH = join(VIDEOS_DIR, "index.ts");

const IMPORTS_START = "// <AUTO_IMPORTS_START>";
const IMPORTS_END = "// <AUTO_IMPORTS_END>";
const ENTRIES_START = "// <AUTO_ENTRIES_START>";
const ENTRIES_END = "// <AUTO_ENTRIES_END>";

type FormatSpec = {
  suffix: string;
  width: number;
  height: number;
  propOverrides?: Record<string, unknown>;
};

type VideoSpec = {
  id: string;
  title: string;
  templateId: "nuptial-promo";
  formats: FormatSpec[];
  script: unknown; // VideoScript — validated structurally below
};

const camelize = (id: string): string => id.charAt(0).toLowerCase() + id.slice(1);

const kebabize = (id: string): string =>
  id
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();

const readSpec = (arg: string | undefined): VideoSpec => {
  let raw: string;
  if (!arg || arg === "-") {
    raw = readFileSync(0, "utf-8");
  } else {
    raw = readFileSync(arg, "utf-8");
  }
  const spec = JSON.parse(raw) as VideoSpec;
  if (!spec.id || !/^[A-Z][A-Za-z0-9]+$/.test(spec.id)) {
    throw new Error(`spec.id must be PascalCase, got "${spec.id}"`);
  }
  if (!spec.title) throw new Error("spec.title is required");
  if (spec.templateId !== "nuptial-promo") {
    throw new Error(`Unknown templateId "${spec.templateId}"`);
  }
  if (!Array.isArray(spec.formats) || spec.formats.length === 0) {
    throw new Error("spec.formats must be a non-empty array");
  }
  if (!spec.script || typeof spec.script !== "object") {
    throw new Error("spec.script is required");
  }
  const script = spec.script as { lines?: unknown[]; scenes?: unknown[]; cta?: unknown };
  if (!Array.isArray(script.lines) || script.lines.length === 0) {
    throw new Error("spec.script.lines must be a non-empty array");
  }
  if (!Array.isArray(script.scenes) || script.scenes.length === 0) {
    throw new Error("spec.script.scenes must be a non-empty array");
  }
  if (!script.cta) throw new Error("spec.script.cta is required");
  return spec;
};

const renderModuleFile = (spec: VideoSpec): string => {
  const exportName = camelize(spec.id);
  return `// Generated by scripts/scaffold-video.ts on ${new Date().toISOString().slice(0, 10)}.
// Re-running the scaffolder with the same id will overwrite this file.

import type { VideoModule } from "./types";

export const ${exportName}: VideoModule = ${JSON.stringify(
    {
      id: spec.id,
      title: spec.title,
      templateId: spec.templateId,
      formats: spec.formats,
      script: spec.script,
    },
    null,
    2,
  )};
`;
};

const replaceBetween = (
  source: string,
  startMarker: string,
  endMarker: string,
  newBody: string,
): string => {
  const startIdx = source.indexOf(startMarker);
  const endIdx = source.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Could not find markers ${startMarker} / ${endMarker} in videos/index.ts`,
    );
  }
  const before = source.slice(0, startIdx + startMarker.length);
  const after = source.slice(endIdx);
  return `${before}\n${newBody}\n${after}`;
};

const updateIndex = (spec: VideoSpec) => {
  const exportName = camelize(spec.id);
  const moduleSlug = kebabize(spec.id);
  let source = readFileSync(INDEX_PATH, "utf-8");

  // Imports
  const importsBody = extractBlock(source, IMPORTS_START, IMPORTS_END);
  const newImportLine = `import { ${exportName} } from "./${moduleSlug}";`;
  const importLines = importsBody
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("//"));
  if (!importLines.includes(newImportLine)) {
    importLines.push(newImportLine);
  }
  importLines.sort();
  source = replaceBetween(
    source,
    IMPORTS_START,
    IMPORTS_END,
    importLines.join("\n"),
  );

  // Entries
  const entriesBody = extractBlock(source, ENTRIES_START, ENTRIES_END);
  const entryLines = entriesBody
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("//"));
  const newEntry = `${exportName},`;
  if (!entryLines.includes(newEntry)) {
    entryLines.push(newEntry);
  }
  entryLines.sort();
  source = replaceBetween(
    source,
    ENTRIES_START,
    ENTRIES_END,
    entryLines.map((l) => `  ${l}`).join("\n"),
  );

  writeFileSync(INDEX_PATH, source);
};

const extractBlock = (source: string, startMarker: string, endMarker: string): string => {
  const startIdx = source.indexOf(startMarker);
  const endIdx = source.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1) return "";
  return source.slice(startIdx + startMarker.length, endIdx).trim();
};

async function run() {
  const spec = readSpec(process.argv[2]);
  const moduleSlug = kebabize(spec.id);
  const moduleFile = join(VIDEOS_DIR, `${moduleSlug}.ts`);

  mkdirSync(dirname(moduleFile), { recursive: true });
  const overwriting = existsSync(moduleFile);
  writeFileSync(moduleFile, renderModuleFile(spec));
  updateIndex(spec);

  const compositions = spec.formats.map((f) => `${spec.id}${f.suffix}`);
  console.log(
    `${overwriting ? "↻" : "✓"} ${moduleSlug}.ts — ${compositions.join(", ")}`,
  );
  console.log(`\nNext:`);
  for (const id of compositions) {
    console.log(`  npm run voiceover ${id}`);
  }
  console.log(`  npm run dev   # preview in Studio`);
}

run().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
